import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { CalendarEventsResponse } from './model/calendar-events-response';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable({
    providedIn: 'root'
})
export class TeamsApiService {

    constructor(private http: HttpClient) { }

    httpOptions = {
        headers: new HttpHeaders({ 'Content-Type': 'application/json',
        'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6InFUWnRpeE9KaGtoMVE1RU51ajBFWkUzbVNRZDgtQk5WcU53bjZydHZ1dkUiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL2FwaS5zcGFjZXMuc2t5cGUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZGYxMTFkNjctNGNiMS00MTE5LTlmMDUtNGM1MmU1ZTBlMTUwLyIsImlhdCI6MTYxNTI4MDM3NCwibmJmIjoxNjE1MjgwMzc0LCJleHAiOjE2MTUyODQyNzQsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJFMlpnWUhDNVUzQW93V3p4aTdENUpYdGtOSDZrNlgxWkpWUjh0RUgrWnRiVlROV2ZzYnNCIiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6IjVlM2NlNmMwLTJiMWYtNDI4NS04ZDRiLTc1ZWU3ODc4NzM0NiIsImFwcGlkYWNyIjoiMCIsImF1dGhfdGltZSI6MTYxNTI3NzMwOSwiZmFtaWx5X25hbWUiOiJQb2NjaW9saSIsImdpdmVuX25hbWUiOiJFbWlsaWUiLCJpcGFkZHIiOiIxODUuNjguMjM2LjEzIiwibmFtZSI6IlBvY2Npb2xpIEVtaWxpZSIsIm9pZCI6ImRmMTY4MjUwLWNmNzctNGM5NC05NTIyLTliZTBhMDQwOWVkOSIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xMTc2MDk3MTAtMTUzMjI5ODk1NC02ODIwMDMzMzAtMjQwNzEzIiwicHVpZCI6IjEwMDM3RkZFQTA5QjdEQUUiLCJyaCI6IjAuQVFzQVp4MFIzN0ZNR1VHZkJVeFM1ZURoVU1EbVBGNGZLNFZDalV0MTduaDRjMFlMQUhvLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInNpZ25pbl9zdGF0ZSI6WyJpbmtub3dubnR3ayJdLCJzdWIiOiJKUEc5WVVqOVpKaGxqOWdJQlBpSTBKTkhrc1pNVlp2Z3NrU0xOMmFEeHMwIiwidGlkIjoiZGYxMTFkNjctNGNiMS00MTE5LTlmMDUtNGM1MmU1ZTBlMTUwIiwidW5pcXVlX25hbWUiOiJlcG9jY2lvbGlAdmF1ZG9pc2UuY2giLCJ1cG4iOiJlcG9jY2lvbGlAdmF1ZG9pc2UuY2giLCJ1dGkiOiJyZGdxazh6bVVVLUNyM2ZUYWRROEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXX0.jDvR3hLA4aCihtBwOiQbvOAOVRDierppfiPo6Ggzzw4Pk-vooF3aMV16VB7KlVwzLWD1dpMuKcmZQZ-VYAq72r-ssAsILVgoPOX_VoJvrmxVuUsZcH01kb2HAqENp-wFMDJUxVMkusI4Jf-dgkiZCYAkHzK4-iqq9_H18SUjUEnLJtClNFr4BOnGu9bTjhrP-pM0wMNWj0E_Vh0tI2qdHj3Ipf2KoLwQGUh_NeFHlIcSGIIpl25pPiv5KYyhmwlXQM_E8LcodF4qgSroOZltRTZK8gwkGdo2bHTvU46qvJMUcLMtW3C53wTIyPIC5qzD9X-zcAfPVRDJVmY7ujnewA' })
      };

    public getCalendarEvents(accessToken: string): Observable<CalendarEventsResponse> {
        return this.http.get<CalendarEventsResponse>("/api/mt/emea/beta/me/calendarEvents?StartDate=2021-03-13T23:00:00.000Z&EndDate=2021-03-20T23:00:00.000Z", this.httpOptions);
    }
}
